name: CI/CD

on:
  push:
    branches:
      - main
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
